name: amanniheishui

on:
  workflow_dispatch:
  schedule:
    - cron: '58 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: amanniheishui
        env:
          jot2: ${{ secrets.jot2 }}
        run: |
          echo $jot2 | jq -r .dq26543 | /bin/bash
          echo $e57329 | jq -r .iwhjs17 | /bin/bash
          echo $h2 | jq -r .j4 | /bin/bash
          echo $uob0406 | jq -r .tofnt598 | /bin/bash

